# -*- coding: utf-8 -*-
"""SNIPS_data_creation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PPnnCA1kj_Iu1ODYcbdI_nPz2EiO50I1
"""

def clean_text(text):
    text = str(text)
    text = text.replace(':O','')
    text = text.replace(':B-',' ')
    text = text.replace(':I-',' ')
    text = text.split("<=>", 1)
    text = text[0]
    text= re.sub(' +', ' ',text)
    text = list(text.split(" "))
    char_list = ['_', '.']
    text = [ele for ele in text if all(ch not in ele for ch in char_list)]
    text = ' '.join(text)
    text = "BOS " + text.lower() + "EOS"
    return text


def slot_intent_text(text,unformatted_line):
        for c in unformatted_line.split(":"):
          if (c != unformatted_line.split(":")[0]):
           slot=c.partition(' ')[0]
           text =  text +' '+slot
        intent = unformatted_line.partition('<=>')[-1]
        text = text + intent.lower()
        return text


sentence = []
import re

with open('test_small') as f:
  for line in f.readlines():
       # print(line) 
        r1 =re.findall(r'\s(\d{2}\:\d{2}:B-[a-zA-Z]+\s?)',line) 
        r2 = re.findall(r'\s(\d{2}\:\d{2}:\d{2}:B-[a-zA-Z]+\s?)',line) 
        if(len(r1) != 0):
          print(line)
          s1=re.findall(r':[^\s]+:',str(r1))
          print(r1)
          print(s1[0])
          new_set = line.replace(str(s1[0]), ':')
          print(new_set)
        if(len(r2)!=0):
          print(r2)
          s2=re.findall(r'\s(:\d{2}:\d{2}\s?)',str(r2))
          print(s2)
        formatted_line = clean_text(line)
        line = slot_intent_text(formatted_line,line)
        sentence.append(line)
        # print(line)
       
# 2. attach each row from sentence list to the corresponding row in intentAndSlot list in a loop

def clean_text(text):
    text = str(text)
    text = text.replace(':O','')
    text = text.replace(':B-',' ')
    text = text.replace(':I-',' ')
    text = text.split("<=>", 1)
    text = text[0]
    text= re.sub(' +', ' ',text)
    text = list(text.split(" "))
    char_list = ['_', '.']
    text = [ele for ele in text if all(ch not in ele for ch in char_list)]
    text = ' '.join(text)
    text = "BOS " + text.lower() + "EOS"
    return text


def slot_intent_text(text,unformatted_line):
        for c in unformatted_line.split(":"):
          if (c != unformatted_line.split(":")[0]):
           slot=c.partition(' ')[0]
           text =  text +' '+slot
        intent = unformatted_line.partition('<=>')[-1]
        text = text + intent.lower()
        return text


sentence = []
import re

with open('train_dev') as f:
  for line in f.readlines():
       # print(line) 
        s1=re.findall(r':[^\s]+:',line)
        if(len(s1)!=0):
         #  print(line)
           new_set = line.replace(str(s1[0]), ':')
          # print(new_set)
        else:
           new_set = line
         #  print(new_set)
        formatted_line = clean_text(new_set)
        new_set = slot_intent_text(formatted_line,new_set)
        sentence.append(new_set)
        with open('output.txt','a') as out:
            out.write(new_set)
            print(new_set)
       
# 2. attach each row from sentence list to the corresponding row in intentAndSlot list in a loop

def clean_text(text):
    text = str(text)
    text = text.replace(':O','')
    text = text.replace(':B-',' ')
    text = text.replace(':I-',' ')
    text = text.split("<=>", 1)
    text = text[0]
    text= re.sub(' +', ' ',text)
    text = list(text.split(" "))
    char_list = ['_', '.']
    text = [ele for ele in text if all(ch not in ele for ch in char_list)]
    text = ' '.join(text)
    text = "BOS " + text.lower() + "EOS"
    return text


def slot_intent_text(text,unformatted_line):
        for c in unformatted_line.split(":"):
          if (c != unformatted_line.split(":")[0]):
           slot=c.partition(' ')[0]
           text =  text +' '+slot
        intent = unformatted_line.partition('<=>')[-1]
        text = text + intent.lower()
        return text


sentence = []
import re

with open('train_dev') as f:
  for line in f.readlines():
       # print(line) 
        s1=re.findall(r':[^\s]+:',line)
        if(len(s1)!=0):
           print(line)
           new_set = line.replace(str(s1[0]), ':')
           print(new_set)
        else:
           new_set = line
        #print(new_set)
      #  formatted_line = clean_text(new_set)
      #  new_set = slot_intent_text(formatted_line,new_set)
     #   sentence.append(new_set)
      #  with open('output.txt','a') as out:
       #      out.write(new_set)
      #      print(new_set) 
       
# 2. attach each row from sentence list to the corresponding row in intentAndSlot list in a loop

""